### ISSUE TITLE
Four Columns

### ISSUE THREAD

**Issue by Ruby-Haruko** [anametologin/krohnkite#36]
Please add an option for Four Columns and more? with a 32:9 Monitor (5120x1440) is a lot of space for more columns.

**Comment by Jas-SinghFSU** [comment]
You should be able to use the vertical layout and rotate it with a rotate keybind assigned to have in infinite columns... at least for now.

**Comment by stylerw** [comment]
As a fellow ultrawide user, I'll second that I'd like a 'Just line them up next to each other, as many as you'd like' sort of thing to get a 3+ column window layout. As for the above @Jas-SinghFSU comment, I can't find a 'Vertical' Layout in the current release which allows me to do this. Help?

**Comment by anametologin** [comment]
>  I can't find a 'Vertical' Layout
Stacked layout

**Comment by stylerw** [comment]
That doesn't quite do what I need, though, as it doesn't equally distribute the window widths. It gives half the screen to one of them. I'm hoping for something that splits the desktop equally among windows. But thank you, and thank you for the  project!

**Comment by anametologin** [comment]
> I'm hoping for something that splits the desktop equally among windows.

Krohnkite is about shortcuts, so you can use shrink/enlarge and rotate shortcuts.

**Comment by stylerw** [comment]
That may be, but it would be nice to have a layout which just displays window in one row, on equal size, which could be rotated vertically or horizontally. Thank you!

**Comment by stylerw** [comment]
For what it's worth, this was implemented previously by Kwin-Tiling under the name 'Blade Layout' (code here: https://github.com/kwin-scripts/kwin-tiling/blob/master/contents/code/bladelayout.js), if that's helpful and saves work.

**Comment by Jas-SinghFSU** [comment]
The work is rather simple for this tiling but I think it's more of a matter of approach. There are three options currently that I can think of that are feasible:

1. We implement a whole new layout for this specific request
2. We provide an option in the Vertical layout to not create a master tile - which would spawn all windows at even sizes
3. We provide an option to also rotate the vertical layout permanently (and maybe even other layouts?) that persists between sessions

Options 2 and 3 go hand in hand for this specific approach but would also provide a better user experience with persisted sessions.

The rest is just a simple matter of implementation.

**Comment by jotapesse** [comment]
Hello @anametologin!

Following up on the @Ruby-Haruko initial request I would like to reinforce and add on this feature request for layouts more suitable for (super-) ultrawide monitors. I'm using a **49" ultrawide 32:9 aspect ratio (5120x1440)** - which I find excellent for work/productivity - and I can confirm that none of the available layouts is suitable for these large ultrawide monitors - at least really not for a large **32:9 aspect ratio**.

The **Three-Column** layout comes close as it allows to split vertically the slave or master columns and possibly it may be enough or work well on smaller 21:9 monitors (not sure, not tested it myself) - but on the 32:9 monitor the columns are way to large (width) waisting too much desktop space and we have no way of adding an extra column. Not optimal at all. Example:

![image](https://github.com/user-attachments/assets/d2b0a723-e9e6-411c-9cc0-9a872400a7fe)

> Krohnkite is about shortcuts, so you can use shrink/enlarge and rotate shortcuts.

Not enough for this use case. Yes, we can use the **Tile** or **Stacked** layouts with **Rotate** as a workaroud for more columns - but then **you are unable to split vertically those rotated columns** to accomodate several smaller windows on the same collumn. Example **Tile[5] + Rotate**:

![image](https://github.com/user-attachments/assets/0270044c-472a-4789-ba49-b79e573605fd)

All other layouts (Monocle, Spiral, Quarter, Spread, Stair and ) are really unusable or impractible for this use case.

:point_right:  **What we really need - based on the Three-Column layout:**
- A **Four-Column** layout, mockup example:

![image](https://github.com/user-attachments/assets/c34403b8-4fef-429e-b900-b3969d10642f)

- A **Fifth-Column** layout, so that we can have up to 5 columns, mockup example:

![image](https://github.com/user-attachments/assets/430dcbb0-3124-4804-a544-8f6024dfa0de)

On my typical workflow I usually vary between 4 or 5 columns. I'm not sure how hard would be to implement those, possibly basing them from the existing **Three-Column** layout, but those **Four-Column** and **Fifth-Column** layouts would really improve the tilinig management and workflow for these ultrawide monitors, both 32:9 and 21:9 asptec ratios. Please, please, please! :pray:

**Comment by Ruby-Haruko** [comment]
Or you can rotate the three-column set, if you have more masters in the middle (easier solution)

**Comment by jotapesse** [comment]
> Or you can rotate the three-column set, if you have more masters in the middle (easier solution)

Not really, you cannot. **Rotate** doesn't work for the **Three-Column** layout. You can **Increase** the Master count - which will vertically split the Master column but the number of 3 columns will be kept the same.

**Comment by Ramblurr** [comment]
@jotapesse 's screenshots above of a 4th and 5th column are exactly what I'm looking for as well! The key is being able to split the side columns which you can't do when using Tile+Rotate

**Comment by anametologin** [comment]
I suggest you new layout `columns` 6c51c4f2add87bc570b9f31615cf31b675482bc5

**Comment by stylerw** [comment]
This 'Columns' layout looks very promising, but building from source right now, the Rotate command doesn't seem to work on this layout (while it does work on 'stacked', so I just get many rows, rather than columns.  Also, I'd argue that this should probably default to many vertical windows, rather than horizontal ones.

**Comment by jotapesse** [comment]
@anametologin Looks promising! I would agree and furher suggest that a new **Multiple-Column** layout (possibly based of the existing **Three-Column** layout and eventually replacing it) would be ideal. **What we need (ideally):**
- Not limited to any number of columns;
- Able to split vertically any column;
- By default adds more columns (not rows);

**Comment by jotapesse** [comment]
@anametologin I just tried the new Columns layout on [krohnkite-0.9.8.1](https://github.com/anametologin/krohnkite/releases/tag/0.9.8.1). Rotate doesn't work. Seems that currently the only way to add columns is by either:
- Keyboard - Krohnkite: Move **Left**/**Right** (move windows left or right to create new columns);
- Mouse - Drag and Drop Windows **Left**/**Right** (to create new columns left or right);

So currently the following needs are met :smile::
- :white_check_mark: Not limited to any number of columns;
- :white_check_mark: Able to split vertically any column;
- :x: By default adds more columns (not rows);

:raised_hands: Great job! :smile: We are almost there! Now my suggestion of improvement would be to add/implement:
- Columns by default (not rows), adds more columns;
- Allow columns vertical spliting by:
  - Keyboard - Krohnkite: Move **Up**/**Down** (move windows up or down to split columns vertically);
  - Mouse - Drag and Drop Windows **Up**/**Down** to split columns vertically);

Thank you for your work so far! :muscle:

**Comment by stylerw** [comment]
Thank you! The rotated columns layout is exactly what I'd wanted, and as far as I'm concerned, this issue is resolved. I really appreciate your work here.
