### ISSUE TITLE
Large unexpected gaps when opening multiple foot terminal emulators

### ISSUE THREAD

**Issue by amarakon** [anametologin/krohnkite#45]
**Symptom**
Whenever I open multiple foot windows using the tile mode, there ends up being unusually large gaps between the windows.

**How to Reproduce**
1. Use the tile layout
2. Launch two or three foot windows

**Expected behavior**
Regular sized gaps between windows, as seen when opening any other window.

**Environment**
 - Distro: CachyOS, based on Arch Linux
 - KWin version: 6.1.3
 - Krohnkite version: 34daf1c
 - List of KWin scripts in use: Krohnkite

**Notes**
Here's a video.

https://github.com/user-attachments/assets/e79a9a3a-3af0-42b6-a4ab-17af4b70c0e6

**Comment by anametologin** [comment]
It's not Krohnkite bug, as I see if every application works well beside this one, the problem in this application.

**Comment by amarakon** [comment]
Are you sure it's not a Krohnkite bug? Why doesn't this happen in tiling Wayland compositors like River and Hyprland?

**Comment by anametologin** [comment]
I tried Polonium - another Kwin tiling script with the same result. May be it is  Kwin bug, I don't know. Krohnkite only use compositor's api.

**Comment by burein-ita** [comment]
Just for future reference:

This is not a bug. This is intended terminal emulator behavior. Terminal emulators traditionally resize in "cell" intervals.

In order to "fix" this many modern terminal emulators have a config option to disable this behavior.

Foot has `resize-by-cells` and `resize-keep-grid` which are enabled by default.

Set them both to `false` inside `foot.ini` and it should fix this issue.

**Comment by Erothas** [comment]
> Just for future reference:
> 
> This is not a bug. This is intended terminal emulator behavior. Terminal emulators traditionally resize in "cell" intervals.
> 
> In order to "fix" this many modern terminal emulators have a config option to disable this behavior.
> 
> Foot has `resize-by-cells` and `resize-keep-grid` which are enabled by default.
> 
> Set them both to `false` inside `foot.ini` and it should fix this issue.

You are literally the best! I have been having this issue for like.. what.. years? I pretty much gave up on foot because of it. I decided to bite the bullet and just create an issue on github to see the end of it, because I simply love the foot terminal. Lo and behold, 6 hours ago, you post the solution, and I just come across it moments ago. This world works in mysterious ways, I tell ya ;) Thanks a lot!
