### ISSUE TITLE
Improvement Request - Always tile a moving windows on mouse release based on the tiling configuration of that monitor 

### ISSUE THREAD

**Issue by andrei93r** [anametologin/krohnkite#70]
**Symptom**

When picking a window with the mouse and drag it by a tiny bit, the window goes in floating mode. A system to prevent this would be greatly appriciated. Moreover, when dragging a window on another screen , it always goes on floating mode. It would be nice to auto-tile based on that screens configuration. Only auto-float windows on mouse release once the window is released on a floating layout

**How to Reproduce**
1. Launch '....'
2. Press key '....'
3. See error

**Expected behavior**
A concise description of what you expected to happen.

**Environment**
 - Distro: [Fedora 40]
 - KWin version: [6.1.4]
 - Krohnkite version: [0.9.7]
 - List of KWin scripts in use: [krohnkite]

**Notes**
Anything that you want to tell developers about.

**Comment by Davey-Hughes** [comment]
This is my biggest feature request. I use KDE because I want the ability to use my mouse to navigate and rearrange windows, but I want the windows to tile by default. It used to work pretty flawlessly in X11 but I know there's been a ton of work to get any of these Kwin scripts working in Wayland.

Here's my env:
- Distro: [6.6.51-1-MANJARO]
- KDE Plasma: [6.1.5]
- Krohnkite version: [0.9.7]
- List of KWin scripts in use: [krohnkite]

**Comment by Davey-Hughes** [comment]
Hey @andrei93r I ended up figuring this out, and will make a PR, but this turns out to be a relatively easy fix I believe.

The issue is that even though the option "keepTilingOnDrag" which corresponds to the option "Always preserve the tiling status of a window upon dragging" isn't being set right. The fix you can do is run the command:
`kwriteconfig6 --file kwinrc --group Script-krohnkite --key keepTilingOnDrag true` 

This can also be done by editing the kwinrc file manually:
1. Open the file: `~/.config/kwinrc`
2. Add a field `keepTilingOnDrag=true` under the section `[Script-krohnkite]`. 

![image](https://github.com/user-attachments/assets/cf6ecbdb-9e54-4d14-a99f-4a9ba67ced66)

You may have to log out and back in for the changes to be reflected.

**Comment by andrei93r** [comment]
@Davey-Hughes 

Hi, 

I just tested this. It works with the provided instructions.

Thank you.
