### ISSUE TITLE
Typo in shortcuts declaration

### ISSUE THREAD

**Issue by WNacci** [anametologin/krohnkite#9]
**Symptom**
There is a single-character typo in the shortcuts.qml file, resulting in the Shrinkheight command not working.

(Line 124 in res/shortcuts.qml)

Additionally, it seems that shrinkheight and growheight might be inverted?

**How to Reproduce**
1. Upon install via the kwin scripts manager, the incorrect shortcut is added

**Environment**
 - Distro: Manjaro/Archlinux
 - KWin version: 6.0.4
 - Krohnkite version: 0.9.3, git commit

**Notes**
Thank you for enabling support for Krohnkite in KDE 6!

**Comment by anametologin** [comment]
I fixed the typo, but keep in mind that the old one does not disappear.
Delete all unused KWin shortcuts:
`qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.cleanUp
` 
I will write this in readme.md. 

> Additionally, it seems that shrinkheight and growheight might be inverted?

It's relatively. Original author meant the south. You mean the North. I do not want to touch the shortcuts because old shortcuts do not disappear itself.
